// <auto-generated />
namespace FinalASM.EF.FPTMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TraineeCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TraineeCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202110120827572_TraineeCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
